<div class="container text-justify">


<p><strong>JUGADA SUPERLIGA</strong></p>
<p><strong>TERMINOS Y CONDICIONES</strong></p>

<p><strong>Última fecha de revisión: 19 de Octubre de 2018.</strong></p>
<p><strong>Bienvenidos a JUGADA SUPERLIGA!</strong></p>
<p>BALL TO BALL S.A.S. (“<strong>BTB</strong>” y/o “<strong>Nosotros</strong>”, indistintamente) proporciona sus servicios exclusivamente a personas que -de acuerdo a la legislación aplicable en su país de residencia- sea considerada mayor de edad (en adelante, “Usuario” y/o “Usuarios”) a través de su aplicación denominada <strong>JUGADA SUPERLIGA </strong>(en adelante, la <strong>“Aplicación</strong>” y/o la “<strong>App</strong>” de manera indistinta) y sus aplicaciones relacionadas (en su conjunto, los servicios y la Aplicación, incluyendo cualquier nueva característica de los mismos, se denominan el "<strong>Servicio (s)</strong>"), sujeto a los siguientes Términos y Condiciones (en adelante, los "<strong>T&amp;C</strong>"). </p>
<p>BTB se reserva el derecho, a su entera discreción, de modificar en todo o en parte los presentes T&amp;C en cualquier momento. El uso continuado del Servicio por parte del Usuario con posterioridad a la fecha en que dichos cambios entraren en vigencia constituye la aceptación por parte del Usuario de los nuevos T&amp;C.</p>
<p>BTB es propietario de la Aplicación, siendo la marca y el nombre de la misma de propiedad exclusiva de la Superliga Profesional del Fútbol Argentino Asoc. Civil, CUIT 30-71554677-5 (la “<strong>Superliga</strong>”). </p>
<p>Los Usuarios que utilicen los Servicios, estarán sujetos a los términos adicionales aplicables a cada servicio en particular (en adelante, los “<strong>Términos Adicionales</strong>”), entre otras, la Política de Privacidad que se encuentra a su disposición en  HYPERLINK "<a href="https://www.jugadasuperliga.com/pages/display/politicas" target="_blank">https://www.jugadasuperliga.<wbr>com/pages/display/politicas</a>" \t "_blank" <a href="https://www.jugadasuperliga.com/pages/display/politicas" target="_blank">https://www.jugadasuperliga.<wbr>com/pages/display/politicas</a>. Todos los Términos Adicionales a los que aquí y a lo largo del presente documento se hace referencia forman parte integrante de los presentes T&amp;C.</p>
<p>Los T&amp;C, los Términos Adicionales y las Políticas de Privacidad rigen el uso de los Servicios.</p>
<p>A pesar de que la App puede proveer o sugerir links o hipervínculos a sitios o aplicaciones de terceros para la conveniencia del Usuario, ello no implica que BTB y/o la Superliga monitorean o avalan algún contenido fuera de los Servicios o la App. Ni BTB ni la Superliga se responsabilizan de manera directa o indirecta por los daños o pérdidas causadas o que puedan causarse por o en conexión con el uso de  la App o de la confianza que el Usuario deposite en cualquier información, contenido, bienes o servicios disponibles en o por medio de cualquier tercero cuyos recursos sean vinculados por medio de los hipervínculos aludidos.</p>

<p><strong>Acceso y Uso de los Servicios</strong></p>
<p><strong>Delimitación geográfica: </strong>Los Servicios y/o la App podrán ser utilizados por cualquier Usuario que sea mayor de edad de acuerdo a la legislación vigente en su país de residencia, por lo que al aceptar los T&amp;C Usted declara y garantiza que  cumple con dicho requisito.</p>

<p><strong>Descripción del Servicio: </strong>Toda persona que quiera utilizar los Servicios, deberá descargar la App desde las tiendas virtuales de App Store o de Google Play o desde el sitio web de la Jugada Superliga ( HYPERLINK "<a href="https://www.jugadasuperliga.com/" target="_blank">https://www.jugadasuperliga.<wbr>com/</a>" \t "_blank" <a href="https://www.jugadasuperliga.com/" target="_blank">https://www.jugadasuperliga.<wbr>com/</a>). Una vez descargada la App en sus dispositivos móviles, será condición para el inicio de su utilización que los Usuarios acepten los T&amp;C como así también las Políticas de Privacidad. Asimismo, Usted entiende y acepta que a fin de poder utilizar la App deberá crearse una cuenta dentro de la App (en adelante, la “<strong>Cuenta de Usuario</strong>”) mediante los sitios de internet y/o aplicaciones móviles de Facebook©, Twitter© o Google©, aceptando y autorizando de esta manera y con su aceptación de los T&amp;C el acceso por parte de BTB a la información de registro que dichas compañías nos proporcionan. Usted entiende y acepta que en caso de considerar que Facebook©, Twitter© o Google© no están cumpliendo en debida forma con el tratamiento de sus datos, BTB no tiene responsabilidad alguna al respecto y deberá el Usuario que así lo considere, efectuar los reclamos correspondientes ante dichas compañías.</p>
<p>Una vez descargada la App en el dispositivo móvil del Usuario, éste ingresará a la App y contará de manera gratuita, por primera y única vez, con una cantidad de vidas ilimitadas (en adelante, “Vidas de Inicio”), para poder comenzar a interactuar en los Servicios. Estas Vidas de Inicio tendrán una vigencia de treinta (30) días corridos a partir del día en que el Usuario se registra por primera vez en la App.</p>
<p>La App cuenta con dos modalidades diferentes de participación:</p>
<ol><li>Durante la temporada de partidos de fútbol de la Superliga, en vivo: el Usuario podrá participar en la App de diferentes trivias que se vayan presentando mientras estén emitiéndose los partidos de fútbol de la Superliga, en vivo, es decir en tiempo real mientras transcurren los partidos. Las trivias consistirán generalmente en a) preguntas con tres (3) opciones de respuestas posibles ante situaciones que se van presentando al Usuario en la App en ocasión de hechos reales que se van suscitando en los partidos de fútbol de la Superliga en tiempo real, como por ejemplo penales, tiros libres, goles, entre otros, que en adelante serán denominados Incidencias. El Usuario contará con una cantidad de segundos determinados para responder, los que serán variables según la pregunta y que le serán informados al momento de aparecer la trivia en las pantallas de los celulares de los Usuarios. En caso de que el Usuario responda de manera correcta, sumará la cantidad de puntos que se informen en cada pregunta. En caso que el Usuario responda de manera incorrecta, no sumará punto alguno y además perderá la cantidad de vidas que se informe en cada pregunta; si el usuario responde una vez transcurridos los segundos informados en cada trivia, perderá el derecho a responder la misma automáticamente, no sumando puntos aún si su respuesta hubiera sido correcta y/o b) preguntas que se le presentarán al Usuario en las pantallas de sus dispositivos móviles que no tendrán que ver con lo que esté ocurriendo en ese mismo momento en el partido de fútbol de la Superliga pero que tendrá algún tipo de relación con el mismo. En este caso, cuando el Usuario responda de manera correcta, sumará la cantidad de puntos que se informen en cada pregunta y si responde de manera incorrecta, no sumará puntos y además perderá la cantidad de vidas que se informe en cada pregunta.</li></ol>
<p>El Usuario entiende y acepta que las siguientes definiciones serán las que se utilizarán en los Servicios para considerar las respuestas a las Incidencias: (ACÁ HAY QUE REFERIR AL LINK DE LAS REGLAS DE JUEGO)</p>
<ol><li>Fuera de los horarios de partidos de la Superliga, mediante trivias: preguntas que se le presentarán al Usuario en las pantallas de sus dispositivos móviles cuando ingresa a la App fuera de los horarios de los partidos de la Superliga, en un momento determinado, a total discrecionalidad de BTB y que tendrán algún tipo de relación con los equipos, los jugadores de la Superliga, limitado al contexto de su actividad deportiva en los Equipos que integren la Superliga al momento de la utilización de la App, y al marco de la Superliga . En este caso, cuando el Usuario responda de manera incorrecta, no sumará puntos y además perderá la cantidad de vidas que se informe en cada pregunta, por el contrario, si responde de manera correcta sumará la cantidad de puntos que se informen en cada pregunta.</li></ol>
<p>Los puntos que obtenga cada Usuario en la medida que participe de alguna de las dos modalidades del Servicio podrán ser canjeados por premios, cuyo detalle, incluyendo la cantidad de puntos necesarios para cada premio y las modalidades de canje se pueden encontrar en   HYPERLINK "<a href="https://www.jugadasuperliga.com/pages/display/premios" target="_blank">https://www.jugadasuperliga.<wbr>com/pages/display/premios</a>" \t "_blank" <a href="https://www.jugadasuperliga.com/pages/display/premios" target="_blank">https://www.jugadasuperliga.<wbr>com/pages/display/premios</a>. El Usuario entiende y acepta que la disponibilidad de los premios es limitada en tiempo y en cantidad según catálogo y/o hasta agotar stock. El Usuario entiende y acepta que BTB se reserva el derecho de estipular que determinados premios serán canjeables única y exclusivamente para determinados partidos y/o para determinadas fechas, información que será detallada en el catálogo que se pondrá a disposición de los Usuarios dentro de la App.  El Usuario reconoce que los premios se otorgarán a los primeros usuarios que respondan correctamente y que una vez agotado el stock, el Usuario no tendrá derecho a reclamo alguno, a pesar de haber respondido correctamente.</p>
<p><strong>Obligaciones del Usuario:</strong> El acceso por cualquier persona a los Servicios mediante su cuenta de Facebook, Google o Twitter le otorga la calificación de Usuario ("<strong>Usuario</strong>" y/o "<strong>Usuarios</strong>" y/o “<strong>Usted</strong>”).<strong> </strong>Si elige registrarse para utilizar los Servicios, el Usuario acepta proporcionar y mantener su información personal veraz, precisa, actualizada y completa. Los datos de registro y cualquier otra información brindada por Usted se regirá por nuestra Política de Privacidad. Si Usted es residente de la República Argentina y tiene menos de trece (13) años de edad, no está autorizado a usar el Servicio, con o sin registro, así como tampoco está autorizado a su uso si Usted es menor de edad según la legislación aplicable a su país de residencia. Al utilizar la Aplicación y/o los Servicios, el Usuario acepta los presentes T&amp;C y nuestra  HYPERLINK "<a href="http://www.etermax.com/es/privacy" target="_blank">http://www.etermax.com/es/<wbr>privacy</a>" Política de Privacidad, por lo que le rogamos los lea con atención. Si no está conforme con los T&amp;C y/o nuestra Política de Privacidad, no utilice nuestros Servicios. Para el caso de los residentes en la República Argentina mayores de trece (13) años pero menores de 18 años, los mismos podrán usar el Servicio únicamente si cuentan con la aprobación de su padre o tutor, la que deberá ser debidamente digitalizada y adjuntada al formulario de Registro correspondiente. El mismo requisito regirá para las personas que según la legislación aplicable en su país de residencia requieran para el ejercicio de sus derechos autorización de sus padres o tutores.</p>
<p><strong>Cuenta de los Usuarios, contraseña y seguridad:</strong> Usted es responsable de mantener la confidencialidad de su contraseña y cuenta, si corresponde, y es totalmente responsable de todas y cada una de las actividades que ocurran bajo su contraseña o cuenta. Usted acepta (a) notificar inmediatamente a BTB de cualquier uso no autorizado de su contraseña o cuenta o cualquier otra violación de la seguridad, y (b) asegurarse de salir de su cuenta al final de cada sesión. BTB y/o la Superliga no serán responsables de ninguna pérdida o daño que surja de su incumplimiento de esta Sección.</p>
<p>BTB se reserva el derecho de modificar y/o suspender los Servicios o alguna parte de ellos, ya sea temporaria o permanentemente sin aviso anticipado al Usuario, sin que de ello se derive derecho a reclamo y/o compensación alguna a favor del Usuario. .</p>
<p><strong>Prácticas generales respecto al uso y almacenamiento:</strong> Usted reconoce que BTB puede establecer prácticas generales y límites con respecto al uso del Servicio. BTB se reserva el derecho de cancelar cuentas de Usuarios inactivas por un período prolongado y/o cuentas que incumplan los T&amp;C o las políticas de BTB o de la Superliga.</p>
<p><strong>Condiciones de Uso</strong></p>
<p><strong>Comportamiento del Usuario:</strong> Usted es el único responsable de todas las fotografías, gráficos, información, datos, textos, software, música, sonido, video, mensajes u otros materiales ("Contenido") que cargue, publique o visualice (en adelante, "Publicación") o envíe por correo electrónico o transmita de cualquier otra manera o utilice a través del Servicio, debiendo ser titular de todos los Derechos de Propiedad Industrial e Intelectual sobre tales contenidos. Los siguientes son ejemplos de Contenidos y/o usos que ilegales o prohibidos por BTB.. Usted acepta no utilizar el Servicio para:</p>
<p>publicar, enviar por correo electrónico o transmitir cualquier Contenido que (i) sea ilegal, dañino, amenazante, abusivo, hostigador, violento, difamatorio, obsceno, pornográfico, calumnioso, invasivo de la privacidad de otra persona, odioso por motivos raciales, étnicos, de género, y/o político, y/u objetable en cualquier modo y a criterio exclusivo de BTB; (ii) Usted no tiene derecho a transmitir bajo ninguna ley o bajo relaciones contractuales o fiduciarias; (iii) plantee o cree un riesgo a la privacidad o seguridad para cualquier persona; (iv) infrinja cualquier propiedad intelectual u otros derechos de propiedad de cualquier persona sea esta humana o jurídica; (v) constituya publicidad no solicitada o no autorizada, materiales promocionales, actividades comerciales y / o ventas, "correo no deseado", "spam", "cartas en cadena", "esquemas piramidales", "concursos", "sorteos" o cualquier otra forma de recopilación de información; (vi) contenga virus de software o cualquier otro código de computación, archivos o programas diseñados para interrumpir, destruir o limitar la funcionalidad de cualquier software de computación o hardware o equipo de telecomunicaciones; o (vii) a juicio exclusivo de BTB, sea objetable o restrinja o inhiba a cualquier otra persona de usar o disfrutar del Servicio, o que pueda exponer a BTB o sus Usuarios a cualquier daño o responsabilidad de cualquier tipo;</p>
<p>suplantar la identidad de cualquier persona o entidad, y/o declarar falsamente y/o tergiversar su suscripción utilizando la información de otra persona o entidad;</p>
<p>solicitar información personal de cualquier persona menor de 18 (dieciocho) años;</p>
<p>recoger o recopilar direcciones de correo electrónico u otra información de contacto de otros Usuarios del Servicio o de la App por medios electrónicos o de otro tipo con el fin de enviar correos electrónicos no solicitados u otras comunicaciones no solicitadas;</p>
<p>anunciar u ofrecer a la venta o comprar cualquier bien o servicio para cualquier propósito comercial que no esté específicamente autorizado;</p>
<p>interferir o interrumpir el Servicio o servidores o redes conectadas al Servicio, o desobedecer los requisitos, procedimientos, políticas o regulaciones de las redes conectadas al Servicio; </p>
<p>violar cualquier legislación local, provincial, nacional o internacional o cualquier regulación que tenga fuerza de ley;</p>
<p>promover o fomentar cualquier actividad criminal, y/o emprender o proporcionar información acerca de actividades ilegales;</p>
<p>obtener de cualquier manera o intentar acceder a fotografías, información o cualquier otro contenido por cualquier medio que no estuviera intencionadamente puesto a disposición o provisto por los Servicios.</p>
<p>BTB se reserva el derecho de investigar e inciar las acciones legales correspondientes contra cualquier persona que, a criterio exclusivo de BTB, infrinja estas disposiciones, incluyendo pero no limitándose a eliminar el contenido ofensivo del Servicio, suspender o cancelar la cuenta de dichos infractores e informarlo a las autoridades de contralor.</p>
<p><strong>Vidas: </strong>Dentro de la App Usted podrá adquirir vidas adicionales para poder participar de los Servicios. Dichas vidas podrán ser adquiridas por los Usuarios mediante su compra dentro de la App de forma individual, en packs o mediante la suscripción full mensual a los Servicios de la App convirtiéndose el Usuario, en este último caso, en Usuario Premium. Las vidas tendrán una vigencia de treinta (30) días corridos a partir de la fecha de su compra. Tanto la compra de vidas como la suscripción a Usuario Premium se podrán realizar mediante tarjeta de crédito o mediante Mercado Pago. A fin de asegurarse que Mercado Pago funciona de manera correcta en su país, le sugerimos a Usted que visite el siguiente sitio web   HYPERLINK "<a href="https://www.mercadopago.com/" target="_blank">https://www.mercadopago.com/</a>" <a href="https://www.mercadopago.com/" target="_blank">https://www.mercadopago.com/</a> . Usted entiende y acepta que en caso de utilizar la opción de compra de vidas por medio de Mercado Pago, dicha transacción queda sujeta a los términos y condiciones de Mercado Pago, no teniendo BTB y/o la Superliga responsabilidad alguna sobre la misma. Usted entiende y acepta que las vidas y los puntos no son dinero real ni pueden ser canjeados por dinero real. BTB puede revocar sus vidas y/o puntos en cualquier momento sin previo aviso, reembolso o compensación, en caso de que: (i) la App y/o los Servicios se suspendan o discontinúen (sujeto a las leyes y regulaciones aplicables); (ii) BTB determine que el fraude u otra conducta ilegal está asociada con su cuenta; (iii) BTB imponga una fecha de vencimiento en el uso de los puntos y/o las vidas en cumplimiento con las leyes y regulaciones aplicables; (iv) su Cuenta de Usuario se rescinda por cualquier motivo (incluida la violación de estos T&amp;C); o (v) Usted se encuentre en mora en el cumplimiento de cualquiera de sus obligaciones con BTB o dejare de mantener una Cuenta de Usuario activa. Usted acepta que BTB tiene el derecho de administrar, regular y/o modificar los derechos que subyacen a dichos puntos y/o vidas y que BTB y/o la Superliga no tendrán ninguna responsabilidad hacia Usted por el ejercicio de este derecho.</p>
<p>Los puntos y/o vidas representan un derecho a obtener ciertos beneficios en los Servicios, pero no representan un saldo acreedor de la moneda real o su equivalente ni reflejan ningún valor almacenado. Los mencionados puntos y/o vidas simplemente constituyen una medida del alcance de sus derechos. LAS COMPRAS O RECARGAS DE PUNTOS Y/O VIDAS PARA ADQUIRIR DICHOS DERECHOS NO SON REEMBOLSABLES. USTED RECONOCE QUE BTB NO ESTÁ OBLIGADO A PROPORCIONAR UN REEMBOLSO POR NINGUNA RAZÓN, Y QUE NO RECIBIRÁ DINERO U OTRA COMPENSACIÓN POR PUNTOS Y/O VIDAS NO UTILIZADOS.</p>
<p>Usted entiende y acepta que BTB se reserva el derecho de modificar las tarifas aplicables a las vidas en cualquier momento a su entera discreción. Para más información respecto de tarifas para la obtención de Vidas, Usted puede enviar un correo electrónico a  HYPERLINK "mailto:<a href="mailto:consultas.jugadasuperliga@gmail.com" target="_blank">consultas.<wbr>jugadasuperliga@gmail.com</a>" <a href="mailto:consultas.jugadasuperliga@gmail.com" target="_blank">consultas.jugadasuperliga@<wbr>gmail.com</a> .</p>
<p><strong>Aviso especial para uso internacional; Controles de exportación:</strong> el software (definido a continuación) disponible en conexión con el Servicio y la transmisión de datos correspondientes, si los hubiera, está sujeto a los controles de exportación de los Estados Unidos. No se puede descargar ningún Software del Servicio o exportarlo o reexportarlo en violación de las leyes de exportación de EE.UU. En caso de que cualquier Usuario descargue o utilice el software lo hará bajo su propio riesgo. Al reconocer la naturaleza global de Internet, Usted acepta cumplir con todas las reglas y leyes locales con respecto a su uso del Servicio, incluso en lo que respecta a la conducta en línea y el contenido aceptable.   </p>
<p><strong>Uso comercial: </strong>a menos que se autorice expresamente en este documento o en el Servicio, Usted acepta no mostrar, distribuir, licenciar, realizar, publicar, reproducir, duplicar, copiar, crear trabajos derivados, modificar, vender, revender, explotar, transferir o transmitir por cualquier medio y con cualquier propósito comercial, cualquier parte del Servicio, uso del Servicio o acceso al Servicio. El Servicio es para su uso personal y por lo tanto instransferible al igual que las vidas adquiridas y los puntos obtenidos por su desempeño, y no puede ser utilizado para emprendimientos comerciales directos o indirectos. </p>

<p><strong>Derechos de Propiedad Intelectual</strong></p>
<p><strong>Contenido del Servicio, software y marcas comerciales:</strong> Usted reconoce y acepta que el Servicio puede contener fotografías y otro contenido ("Contenido del servicio") que está protegido por derechos de autor, patentes, marcas comerciales, secretos comerciales u otros derechos y otros derechos y leyes de propiedad. Excepto por lo expresamente autorizado por BTB, usted acepta no modificar, copiar, enmarcar, raspar, alquilar, arrendar, prestar, vender, distribuir o crear trabajos derivados y/o basados ​​en el Servicio o el Contenido del Servicio, en su totalidad o en parte. En relación con el uso que Usted haga del Servicio, no deberá participar ni utilizar ningún método de extracción de datos, robots, raspado o recopilación de datos o extracción de datos similares. Cualquier uso de la App o del Contenido del Servicio que no esté específicamente autorizado aquí está estrictamente prohibido. La tecnología y el software subyacentes al Servicio o distribuidos en conexión con ellos son propiedad de BTB, nuestros afiliados y nuestros socios (el "Software"). Usted acuerda no copiar, modificar, crear un trabajo derivado, realizar ingeniería inversa, ensamblar inversamente o de otra manera intentar descubrir cualquier código fuente, vender, asignar, sublicenciar o transferir de otro modo cualquier derecho en el Software. BTB se reserva todos los derechos no otorgados expresamente en este documento.</p>
<p>El nombre y el logotipo de Jugada Superliga son marcas comerciales de la Superliga (colectivamente, las "Marcas comerciales de la “Superliga"). Los nombres y logotipos de otras compañías, productos y servicios utilizados y mostrados a través del Servicio pueden ser marcas comerciales o marcas de servicio de sus respectivos propietarios que pueden o no respaldar o estar afiliados o conectados con BTB y/o la Superliga. Nada en estos T&amp;C o en los Servicios debe interpretarse como la concesión, por implicación, preclusión o de otro modo, de cualquier licencia o derecho a usar cualquiera de las Marcas Comerciales de BTB, de la Superliga y/o de terceros que se muestran en el Servicio. </p>
<p><strong>Contenido del usuario publicado en la App:</strong> En caso que la App posibilite a los Usuarios publicar contenido en los Servicios, Usted será el único responsable del contenido y/u otros materiales que publique en o través de los Servicios o la App, o que transmita o comparta con otros Usuarios o destinatarios (colectivamente, "Contenido del Usuario"). En tal caso, Usted se compromete a no publicar ninguna fotografía, contenido u otro material que no haya creado o que no le pertenezca por derecho, o título alguno, incluidos, entre otros, todos los derechos de autor y los derechos de publicidad contenidos en el mismo. Al publicar cualquier Contenido de usuario, usted otorga a BTB y sus compañías afiliadas una licencia no exclusiva, mundial, libre de regalías, costo y/o cargo alguno; transferible; sublicenciable; perpetua e irrevocable para copiar, visualizar, transmitir, ejecutar, distribuir, almacenar, modificar y usar su Contenido de Usuario en relación con la operación del Servicio o la promoción, publicidad o comercialización de los mismos, en cualquier forma, medio o tecnología ahora conocida, creada o a crearse.</p>
<p>Usted reconoce y acepta que BTB puede conservar Contenido y/o Contenido del Usuario y también puede divulgarlo si así lo exige la ley o si cree de buena fe que dicha preservación o divulgación es razonablemente necesaria para: (a) cumplir con procesos legales, leyes aplicables o solicitudes gubernamentales ; (b) hacer cumplir estos T&amp;C; (c) responder a reclamos de que cualquier contenido viola los derechos de terceros; o (d) proteger los derechos, la propiedad o la seguridad personal de BTB, sus Usuarios y/o el público en general. Usted comprende que el procesamiento y la transmisión técnica del Servicio, incluido su contenido, puede involucrar (a) transmisiones en varias redes; y (b) cambios para cumplir y adaptarse a los requisitos técnicos de conexión de redes o dispositivos.</p>
<p><strong>Comentarios del usuario: </strong>Usted reconoce y acepta que cualquier pregunta, comentario, sugerencia, idea u otra información sobre la App o el Servicio ("Envíos"), proporcionada por Usted a BTB no son confidenciales y BTB tendrá derecho a su uso y difusión de manera irrestricta de los mismos para cualquier propósito, comercial o de otro tipo, sin que de ello se derive reconocimiento o compensación alguna para Usted. </p>
<p><strong>Reclamos por violación a la Propiedad Intelectual: </strong>BTB respeta los derechos de propiedad intelectual de sus Usuarios y de terceros. Es por ello que les exigimos a nuestros Usuarios que respeten los derechos ajenos. Si Usted considera que su derecho de propiedad intelectual ha sido violado, deberá notificar a BTB de dicha violación de acuerdo al procedimiento que a continuación se describe:</p>
<p>El usuario deberá remitir a BTB una notificación de infracción de derechos de autor reclamada por correo electrónico al Agente de derechos de autor de BTB a  HYPERLINK "mailto:<a href="mailto:consultas.jugadasuperliga@gmail.com" target="_blank">consultas.<wbr>jugadasuperliga@gmail.com</a>" <a href="mailto:consultas.jugadasuperliga@gmail.com" target="_blank">consultas.jugadasuperliga@<wbr>gmail.com</a> (Asunto: "Solicitud de eliminación de DMCA"). BTB procesará e investigará los avisos de supuestas infracciones a los derechos de propiedad intelectual y tomará las medidas adecuadas en virtud de la Ley estadounidense de protección de los derechos de autor ("DMCA") y otras leyes de propiedad intelectual aplicables con respecto a cualquier infracción presunta o real.</p>

<p>También puede contactarnos por correo o fax a:</p>

<p>Santa Fe 1211, piso 11, Rosario, Santa Fe, Argentina/ Fax: (0341) 5308194, interno 100</p>

<p>Para que dicha notificación sea válida deberá enviarse por escrito y contener la siguiente información: </p>

<ul><li>firma electrónica o manuscrita del titular del derecho de propiedad intelectual y/o de la persona autorizada a actuar en su nombre y representación;</li></ul>
<li>Si actúa en nombre y representación de un tercero, deberá acompañar el ´documento que acredite el referido mandato y/o personería.</li>
<li>una descripción del derecho de propiedad intelectual que el Usuario o tercero considera que ha sido violado;</li>
<li>una descripción de dónde, en la App o los Servicios, se encuentra el material protegido por el derecho de propiedad intelectual que considera que ha sido violado; </li>
<li>Datos de contacto que deberán incluir: su nombre, dirección, número telefónico y correo electrónico; y una declaración consintiendo la jurisdicción de los tribunales ordinarios de la Ciudad Autónoma de Buenos Aires.</li>
<li>una declaración del Usuario de su Buena fe en la que asegure que la utilización del derecho de propiedad intelectual que considera que ha sido violado no cuenta con autorización de su parte ni de alguna persona que tenga derecho a autorizarlo en su nombre ni que se encuentre autorizado por ley;</li>
<li>una declaración suya, hecha de iniciársele las acciones legales que pudieren corresponder, de que la información anterior en su aviso es exacta y de que Usted es el propietario de los derechos de autor o propiedad intelectual o está autorizado para actuar en nombre del propietario de los derechos de autor o de la propiedad intelectual.</li>
<p><strong>Contranotificación:</strong> si Usted considera que el Contenido de Usuario que se eliminó (o cuyo acceso se inhabilitó) no infringe derechos de propiedad intelectual de terceros, o que Usted cuenta con la autorización del propietario del derecho de propiedad intelectual o cuenta con derecho en virtud de la ley, para publicar y/o utilizar el Contenido en su Contenido de Usuario, puede enviar una contranotificación escrita que contenga la siguiente información al Agente de derechos de autor:</p>
<ul><li>firma manuscrita o electrónica;</li></ul>
<li>identificación del Contenido de Usuario que ha sido removido o cuyo acceso ha sido deshabilitado y la ubicación en la que aparecía el Contenido de Usuario antes de que fuera removido;</li>
<li>una declaración de buena fe de que el Contenido de Usuario que ha sido removido o inhabilitado lo ha sido por error o falta de una correcta identificación del mismo;</li>
<li>su nombre, dirección, número telefónico y correo electrónico; una declaración consintiendo la jurisdicción de los tribunales Nacionales Ordinarios con asiento la Ciudad Autónoma de Buenos Aires y una declaración de que recibió la notificación del reclamo del Usuario y/o tercero que notificó a BTB la supuesta violación del derecho de propiedad intelectual.</li>
<p>Si el Agente de derechos de autor recibe una contranotificación, BTB enviará una copia de la misma a la parte reclamante original para informarle que puede reemplazar el Contenido de Usuario eliminado o dejar de inhabilitarlo en 10 (diez) días hábiles. A menos que el propietario de los derechos de autor presente una acción buscando una orden judicial contra el proveedor de contenido, miembro o usuario, el contenido eliminado puede ser reemplazado, o puede restablecerse, en 10 (diez) días hábiles o más después de recibir la contranotificación, a exclusiva discreción de BTB.</p>
<p><strong>Usuarios reincidentes:</strong> De acuerdo con la DMCA y otras leyes aplicables, BTB adopta una política de cancelación del acceso y uso de la App y los Servicios por parte de los usuarios que se consideran infractores reincidentes, en circunstancias apropiadas y según su exclusiva discrecionalidad. BTB también puede, a su exclusiva discrecionalidad, limitar el acceso a los Servicios y/o a la App y/o rescindir la membrecía de cualquier Usuario que infrinja cualquier derecho de propiedad intelectual de otros Usuarios y/o de terceros, independientemente de que haya o no una reincidencia.</p>
<p><strong>Aplicaciones de software habilitadas por Apple</strong></p>
<p>BTB ofrece la App mediante productos comercializados por Apple Inc. (en adelante, "<strong>Apple</strong>"), entre otras plataformas. Con respecto al Software que está disponible para su uso en conexión con un producto de la marca Apple (en adelante denominado como, "Software habilitado por Apple"). Con relación al Software habilitado por Apple y adicionalmente a los presentes T&amp;C, los siguientes términos y condiciones que se detallan a continuación, (en adelante, “Términos de Servicio”) serán igualmente aplicables a los Usuarios, quienes declaran conocer y aceptar cuanto sigue:</p>
<ul><li>BTB y Usted reconocen que estos T&amp;C se celebran entre BTB y Usted, y no con Apple, y que,  BTB es el único responsable del Software habilitado para Apple y su Contenido;</li></ul>
<p>No puede usar el software habilitado por Apple de ninguna manera que viole o sea incompatible con las reglas de uso establecidas para el software habilitado por Apple, o que infrinja los Términos de servicio de la tienda de aplicaciones de Apple;</p>
<ul><li>Su licencia para usar el Software habilitado por Apple está limitada a una licencia no transferible para usar el software habilitado por Apple en un producto iOS que Usted posee o controla, según lo permitido por las reglas de uso establecidas en los términos de servicio de la tienda de aplicaciones de Apple;</li></ul>
<li>Apple no cuenta con obligación alguna de proveer servicio de mantenimiento o soporte técnico respecto del software habilitado por Apple;</li>
<li>Apple no es responsable de ninguna garantía del producto, ya sea expresa o implícita por ley. En caso de alguna falla del Software habilitado por Apple a fin de cumplir con cualquier garantía vigente, Usted puede notificar a Apple, y Apple le reembolsará el precio de compra del Software compatible con Apple, si correspondiera y hasta cubrir la máxima extensión autorizada por la ley aplicable. Apple no tendrá ninguna otra obligación de garantía con respecto al Software habilitado por Apple, o cualquier otro reclamo, pérdida, responsabilidad, daños, costos o gastos atribuibles a cualquier incumplimiento de cualquier garantía, siendo el único responsable de ello BTB, en la medida y con el alcance que corresponda.</li>
<li>BTB y Usted reconocen que BTB, es la única responsable de abordar cualquier reclamo suyo o de un tercero relacionado con el Software habilitado por Apple o su posesión y/o uso de ese Software habilitado por Apple, que incluye, entre otros: (i) reclamos de responsabilidad del producto; (ii) cualquier reclamo de que el Software habilitado por Apple no cumple con los requisitos legales o reglamentarios aplicables; y (iii) reclamos que surjan bajo el derecho de protección al consumidor o legislación similar.  </li>
<p>En caso de que un tercero afirme que el Software habilitado por Apple o la posesión y el uso por parte del Usuario de ese Software habilitado por Apple infringe los derechos de propiedad intelectual de ese tercero, entre BTB y Apple, BTB, será la única responsable de la investigación, defensa, arreglo y descarga de cualquier reclamo por violación de propiedad intelectual.</p>
<ul><li>Usted declara y garantiza que (i) no se encuentra en un país que está sujeto a un embargo del gobierno de EE. UU. O que ha sido designado por el gobierno de EE. UU. como un país "que apoya el terrorismo"; y (ii) usted no figura en ninguna lista del gobierno de los EE. UU. de partes prohibidas o restringidas.</li></ul>
<p>Si Usted tiene alguna consulta, queja o reclamo con respecto al Software habilitado por Apple, deberá comunicarse con BTB al siguiente contacto:</p>
<p>HYPERLINK "mailto:<a href="mailto:consultas.jugadasuperliga@gmail.com" target="_blank">consultas.<wbr>jugadasuperliga@gmail.com</a>" <a href="mailto:consultas.jugadasuperliga@gmail.com" target="_blank">consultas.jugadasuperliga@<wbr>gmail.com</a> </p>
<p>Dirección: Santa Fe 1211, piso 11, Rosario, Santa Fe, Argentina.</p>
<ul><li>BTB y Usted reconocen y aceptan que Apple y sus subsidiarias son terceros beneficiarios de estos Términos de Servicio con respecto al Software habilitado por Apple, y que, una vez que Usted acepte los términos y condiciones de estos Términos de Servicio, Apple tendrá derecho (y se considerará que ha aceptado el derecho) de hacer cumplir estos Términos de Servicio en su contra con respecto al Software habilitado por Apple como un tercero beneficiario del mismo.</li></ul>
<p><strong>Sitios web de terceros</strong></p>
<p>El Servicio y/o terceros relacionados comercialmente con Nosotros podrán proporcionar, enlaces u otros accesos a otros sitios y recursos en Internet. Ni BTB ni la Superliga tienen control sobre dichos sitios y recursos, y en consecuencia ni BTB ni la Superliga se responsabilizan ni respaldan dichos sitios y recursos. Además, Usted reconoce y acepta que ni BTB ni la Superliga serán responsables ni tendrán a su cargo, de manera directa o indirecta, ningún daño o pérdida causada o presuntamente causada por o en relación con el uso o dependencia de cualquier contenido, evento, producto o servicio disponible en o a través de cualquier sitio o recurso. Cualquier trato que tenga con terceros durante el uso de los Servicios se establece entre Usted y el tercero, y Usted acepta que tanto BTB como la Superliga no son responsables de ninguna pérdida o reclamo que pueda tener contra dicho tercero.</p>

<p><strong>Servicios de terceros</strong></p>
<p>El Usuario puede habilitar varios servicios en línea (por ejemplo, Facebook, Instagram, Twitter, etc.) para que se integren directamente en su experiencia BTB. Al integrar directamente estos servicios en los Servicios de BTB, hacemos que sus experiencias en línea sean más ricas y más personalizadas. Para aprovechar estas características, podemos solicitarle que se registre o inicie sesión en los servicios en los sitios web de sus respectivos proveedores. Al habilitar los servicios de terceros dentro de los Servicios de BTB, nos permite pasar su información de inicio de sesión a estos proveedores de servicios para este fin. Para obtener más información sobre las implicaciones de activar estos servicios de terceros y el uso de la App, almacenamiento y divulgación de información relacionada con Usted y su uso de dichos servicios dentro de BTB (incluidas sus listas de amigos y similares), consulte nuestra Política de Privacidad en   HYPERLINK "<a href="https://www.jugadasuperliga.com/pages/display/politicas" target="_blank">https://www.jugadasuperliga.<wbr>com/pages/display/politicas</a>" \t "_blank" <a href="https://www.jugadasuperliga.com/pages/display/politicas" target="_blank">https://www.jugadasuperliga.<wbr>com/pages/display/politicas</a>. Sin embargo, recuerde que la forma en que los servicios de terceros usan, almacenan y/o divulgan su información se rige únicamente por las políticas de privacidad y/o políticas de datos de dichos terceros, y ni BTB ni Superliga son responsables de las prácticas de privacidad u otras acciones de un sitio de terceros o servicio que puede habilitarse dentro del uso que Usted haga de los Servicios de BTB.</p>
<p>Además, BTB no es responsable de la precisión, disponibilidad o confiabilidad de ninguna información, contenido, bienes, datos, opiniones, consejos o declaraciones disponibles en relación con servicios de terceros. Como tal, BTB no es responsable por ningún daño o pérdida causada o supuestamente causada por o en relación con el uso o dependencia de dicho servicio de terceros. BTB habilita estas características simplemente como una herramienta para el Usuario y la inclusión de tales características no implica una promoción o recomendación de ningún tipo.</p>

<p><strong>Indemnidad y exclusión de responsabilidad</strong></p>
<p>Usted acepta mantener indemne tanto a BTB como a la Superliga, sus afiliados y/o sus funcionarios, empleados, directores y agentes, de cualquier pérdida, gasto, incluidos los honorarios de abogados, derechos, reclamos, acciones de cualquier tipo, daños y perjuicios (incluyendo pero no limitándose al fallecimiento) que surjan de o estén relacionados con el uso de los Servicios; con cualquier Contenido del Usuario; su conexión con el Servicio; por su violación de estos T&amp;C; y/o por su violación de cualquier derecho de terceros.  </p>

<p><strong>Declaración de garantías</strong></p>
<p>EL USO DE LOS SERVICIOS POR PARTE DE LOS USUARIOS ES BAJO SU PROPIO RIESGO. LOS SERVICIOS SE PROPORCIONAN "TAL CUAL ESTAN" Y "SEGÚN DISPONIBILIDAD". BTB NIEGA EXPRESAMENTE TODAS LAS GARANTÍAS DE CUALQUIER TIPO, YA SEAN EXPRESAS, IMPLÍCITAS O ESTATUTARIAS, INCLUIDAS, ENTRE OTRAS PERO NO LIMITANDOSE A LAS GARANTÍAS IMPLÍCITAS DE MERCADO O ADECUADAS PARA UN DETERMINADO PROPÓSITO, TÍTULO Y/O DE VIOLACION DE DERECHO DE PROPIEDAD INTELECTUAL.</p>
<p>BTB NO GARANTIZA QUE (I) LOS SERVICIOS CUMPLIRÁN SUS EXPECTATIVAS, (II) LOS SERVICIOS SERÁN ININTERRUMPIDOS, OPORTUNOS, SEGUROS O LIBRES DE ERRORES, (III) LOS RESULTADOS QUE SE PUEDAN OBTENER DEL USO DE LOS SERVICIOS SERÁN EXACTOS O CONFIABLES, Y/O (IV) LA CALIDAD DE CUALQUIER FOTOGRAFÍA, PRODUCTO, SERVICIO, INFORMACIÓN U OTRO MATERIAL OBTENIDO POR USTED A TRAVÉS DEL SERVICIO CUMPLIRÁ SUS EXPECTATIVAS.</p>

<p><strong>Limitación de responsabilidad</strong></p>
<p>USTED ENTIENDE Y ACEPTA EXPRESAMENTE QUE TANTO BTB COMO LA SUPERLIGA NO SERÁN RESPONSABLES POR DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENCIALES, EJEMPLARES O DAÑOS POR PÉRDIDAS DE BENEFICIOS, INCLUIDOS, ENTRE OTROS, DAÑOS Y PERJUICIOS POR PÉRDIDAS DE BIENES, USO, DATOS U OTRAS PÉRDIDAS INMATERIALES (INCLUSO SI BTB HA SIDO INFORMADO DE LA POSIBILIDAD DE DICHOS DAÑOS), YA SEA BASADO EN CONTRATO, AGRAVIO, NEGLIGENCIA, RESPONSABILIDAD ESTRICTA O DE OTRO MODO, RESULTANTE DE: (I) EL USO O LA INCAPACIDAD DE USAR EL SERVICIO; (II) EL COSTO DE LA ADQUISICIÓN DE BIENES Y SERVICIOS SUSTITUTOS COMO RESULTADO DE CUALQUIER BIEN, DATO, INFORMACIÓN O SERVICIO OBTENIDO O MENSAJES RECIBIDOS O TRANSACCIONES REALIZADAS A TRAVÉS O DESDE EL SERVICIO; (III) ACCESO NO AUTORIZADO O ALTERACIÓN DE SUS TRANSMISIONES O DATOS; (IV) DECLARACIONES O CONDUCTA DE CUALQUIER TERCERO EN LOS SERVICIOS; O (V) CUALQUIER OTRO ASUNTO RELACIONADO CON LOS SERVICIOS. EN NINGÚN CASO LA RESPONSABILIDAD TOTAL DE BTB y/o LA SUPERLIGA ANTE USTED POR TODOS LOS DAÑOS, PÉRDIDAS O CAUSAS DE ACCIÓN ALGUNA EXCEDERÁ LA CANTIDAD DE CIEN DÓLARES ESTADOUNIDENSES (U$S100). SI NO ESTÁ SATISFECHO CON CUALQUIER PARTE DEL SERVICIO O CON ESTOS T&amp;C, SU ÚNICO Y EXCLUSIVO RECURSO ES DEJAR DE USAR LOS SERVICIOS.</p>

<p><strong>Resolución de controversias</strong></p>
<p>Estos Términos y Condiciones de Servicio se regirán e interpretarán de conformidad con las leyes de - la República Argentina. Todas las reclamaciones, procedimientos legales o litigios que surjan en relación con los Servicios y/o a los T&amp;C, que no se resuelvan de mutuo acuerdo, serán presentados únicamente ante los tribunales Nacionales Ordinarios con asiento en la Ciudad Autónoma de Buenos Aires. Usted consiente a la jurisdicción y sede de tales tribunales y renuncia a cualquier objeción de inconveniencia de foro.</p>

<p><strong>Finalización</strong></p>
<p>Usted acepta que BTB puede suspender o cancelar su cuenta de Usuario dentro de los Servicios, o parte de ella, o el uso de los Servicios y/o eliminar y/o descartar cualquier fotografía u otro contenido dentro de los Servicios, a su entera discreción, por cualquier motivo, incluyendo, entre otros, falta de uso o si BTB considera que dicha cuenta y/o uso ha violado o actuado de manera inconsistente con la letra o el espíritu de estos T&amp;C. Cualquier sospecha de actividad fraudulenta, abusiva o ilegal que pueda ser motivo de finalización de su uso de los Servicios, puede ser remitida a las autoridades policiales correspondientes. BTB también puede, a su exclusivo criterio y en cualquier momento suspender la prestación de los Servicios, o cualquier parte del mismo, con o sin previo aviso. Usted acepta que cualquier finalización de su acceso a los Servicios bajo cualquier disposición de estos T&amp;C se puede efectuar sin previo aviso, y reconoce y acepta que BTB puede desactivar o eliminar inmediatamente su cuenta de Usuario dentro de los Servicios y/o toda la información y/o archivos relacionados y/o bloquear cualquier acceso posterior a dichos archivos y/o a los Servicios. Además, Usted acepta que ni BTB ni la Superliga serán responsables ante Usted ni ante ningún Usuario o tercero por la finalización de su acceso a los Servicios.</p>

<p><strong>Disputas del usuario</strong></p>
<p>Usted acepta que Usted es el único responsable de sus interacciones con cualquier otro Usuario en relación con los Servicios y que BTB no tiene ni tendrá responsabilidad alguna con respecto a ello. BTB se reserva el derecho, pero no tiene la obligación, de participar de cualquier forma en las disputas entre usted y cualquier otro Usuario de los Servicios.</p>

<p><strong>General</strong></p>
<p>Estos T&amp;C constituyen el acuerdo completo entre Usted y BTB y rigen el uso de la App y/o los Servicios, reemplazando cualquier acuerdo anterior entre Usted y BTB con respecto a los Servicios. También puede estar sujeto a términos y condiciones adicionales que puedan aplicarse cuando utiliza servicios de afiliados o de terceros, contenido de terceros o software de terceros. Estos T&amp;C se regirán por las leyes de la República Argentina, sin tener en cuenta las disposiciones sobre conflicto de leyes. Con respecto a cualquier disputa o reclamo Usted y BTB acuerdan someterse a la jurisdicción personal y exclusiva de los tribunales Nacionales Ordinarios con asiento en la Ciudad Autónoma de Buenos Aires. La falla de BTB para ejercer o hacer cumplir cualquier derecho o disposición de estos T&amp;C no constituirá una renuncia a tal derecho o disposición. Si un tribunal de jurisdicción competente determina que una disposición de estos T&amp;C es inválida, las partes aceptan que el tribunal debe esforzarse por hacer efectivas las intenciones de las partes tal como se refleja en la disposición y las demás disposiciones de estos T&amp;C permanecerán vigentes. Una versión impresa de este acuerdo y de cualquier notificación dada en forma electrónica será admisible en procedimientos judiciales o administrativos basados ​​o relacionados con este acuerdo, en la misma medida y sujetos a las mismas condiciones que otros documentos y registros comerciales originalmente generados y mantenidos en forma impresa. Los títulos de las secciones en estos T&amp;C son solo a los fines prácticos de la lectura por parte de los Usuarios pero   no tienen ningún efecto legal o contractual. Las notificaciones a los Usuarios pueden hacerse a través de correo electrónico o correo ordinario. Los Servicios también pueden proporcionarle a los Usuarios avisos de cambios a estos T&amp;C u otros asuntos mediante la visualización de avisos o enlaces a avisos publicados en los Servicios.</p>

<p><strong>Privacidad</strong></p>
<p>BTB respeta la privacidad de sus Usuarios. Para más detalles, consulte nuestra Política de Privacidad. Al utilizar los Servicios, Usted acepta la recopilación y uso de datos personales como se describe en dicho documento.</p>

<p><strong>¿Preguntas? ¿Consultas? ¿Sugerencias?</strong></p>
<p>Comuníquese con nosotros a  HYPERLINK "mailto:<a href="mailto:consultas.jugadasuperliga@gmail.com" target="_blank">consultas.<wbr>jugadasuperliga@gmail.com</a>" <a href="mailto:consultas.jugadasuperliga@gmail.com" target="_blank">consultas.jugadasuperliga@<wbr>gmail.com</a> para informar cualquier infracción de estos T&amp;C o para formular preguntas sobre los mismos o sobre los Servicios o para realizar cualquier consulta o sugerencia.</p>








<p>	</p>


</div>